### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Bilbo77-Formulario-con-HTML5#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- ¡Muy buen proyecto @Bilbo77   ... ¡Felicidades!
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- En esta etiqueta`<meta>` tienes un error 
![Captura de pantalla de 2024-03-14 16-29-04](https://github.com/4GeeksAcademy/Bilbo77-Formulario-con-HTML5/assets/139759297/094f780d-5687-46a8-89b3-f216d59c8004)
Debería ser `width=device-width` en lugar de `width=>`
- Esta sintaxis también es incorrecta ![Captura de pantalla de 2024-03-14 16-32-21](https://github.com/4GeeksAcademy/Bilbo77-Formulario-con-HTML5/assets/139759297/9a97e752-390b-406d-bc67-9b8f31e62f3f)
- Recuerda que los IDs deben ser únicos en el documento 
![Captura de pantalla de 2024-03-14 16-33-36](https://github.com/4GeeksAcademy/Bilbo77-Formulario-con-HTML5/assets/139759297/cc0caf3b-d29a-4e5b-b0e4-cc28312e3270)

**Comment by Bilbo77** [comment]
En la primera etiqueta no sabría explicar porqué no está completa, supongo que habrá sido un despiste, anotado queda.
En la segunda etiqueta metí una clase de styles.css en boostrap, no se usa.
En los #id se me olvidó cambiar el último número por 2 y 3, al copiar y pegar se me fue.

**Comment by EduardoHernandezGuzman** [comment]
Buen trabajo
